name: qmc
channels:
  - pytorch
  - https://repo.continuum.io/pkgs/free
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.1.23
  - certifi=2018.11.29
  - cffi=1.12.1
  - cudatoolkit=8.0
  - freetype=2.9.1
  - intel-openmp=2019.1
  - jpeg=9b
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.36
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - ncurses=6.1
  - ninja=1.8.2
  - numpy=1.16.2
  - numpy-base=1.16.2
  - olefile=0.46
  - openssl=1.1.1b
  - pillow=5.4.1
  - pip=19.0.3
  - pycparser=2.19
  - python=3.7.2
  - pytorch=1.0.1
  - readline=7.0
  - setuptools=40.8.0
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.8
  - torchvision=0.2.2
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==3.1.0
    - box2d-py==2.3.8
    - chaospy==3.0.11
    - chardet==3.0.4
    - cycler==0.10.0
    - cython==0.29.10
    - decorator==4.3.2
    - defusedxml==0.5.0
    - dill==0.2.9
    - entrypoints==0.3
    - filelock==3.0.10
    - future==0.17.1
    - glfw==1.8.1
    - gym==0.12.0
    - idna==2.8
    - imageio==2.5.0
    - ipdb==0.11
    - ipykernel==5.1.0
    - ipython==7.3.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jedi==0.13.3
    - jinja2==2.10
    - jsonschema==3.0.1
    - jupyter==1.0.0
    - jupyter-client==5.2.4
    - jupyter-console==6.0.0
    - jupyter-core==4.4.0
    - kiwisolver==1.0.1
    - llvmlite==0.27.1
    - lockfile==0.12.2
    - markupsafe==1.1.1
    - matplotlib==3.0.3
    - mistune==0.8.4
    - mujoco-py==2.0.2.2
    - nbconvert==5.4.1
    - nbformat==4.4.0
    - notebook==5.7.6
    - numba==0.42.1
    - panda==0.3.1
    - pandas==0.24.1
    - pandocfilters==1.4.2
    - parso==0.3.4
    - particles==0.1
    - pexpect==4.6.0
    - pickleshare==0.7.5
    - prometheus-client==0.6.0
    - prompt-toolkit==2.0.9
    - ptyprocess==0.6.0
    - pyglet==1.3.2
    - pygments==2.3.1
    - pyparsing==2.3.1
    - pyrsistent==0.14.11
    - python-dateutil==2.8.0
    - pytz==2018.9
    - pyzmq==18.0.1
    - qtconsole==4.4.3
    - requests==2.21.0
    - scipy==1.2.1
    - seaborn==0.9.0
    - send2trash==1.5.0
    - sobol-seq==0.1.2
    - termcolor==1.1.0
    - terminado==0.8.1
    - testpath==0.4.2
    - tornado==6.0.1
    - tqdm==4.31.1
    - traitlets==4.3.2
    - urllib3==1.24.1
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.4.2

